#!/bin/sh
set -e

lb config noauto \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --binary-images iso-hybrid \
    --debian-installer none \
    --linux-flavours amd64 \
    --security true \
    --memtest none \
    --checksums sha256 \
    --iso-application "mayxcloudos" \
    --iso-publisher "MâyXCloud" \
    --iso-volume "MAYXCLOUDOS" \
    --bootappend-live "boot=live components quiet username=may hostname=mayxcloudos locale=vi_VN.UTF-8 timezone=Asia/Ho_Chi_Minh keyboard-layouts=us"
